name: Update Suttas List

on:
  push:

jobs:
  update-suttas-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies here if needed

      - name: Run available_suttas.py script
        run: python available_suttas.py

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --exit-code; then
              echo "::set-output name=changes::false"
          else
              echo "::set-output name=changes::true"
          fi

      - name: Commit and push if changes
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add available_suttas.json
          git pull --rebase
          git commit -m "Update available suttas list" -a
          git push