name: Update Suttas List

on:
  push:
    paths:
      - 'suttas/translation_en/*.json'

jobs:
  update-suttas-list:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # Add any other dependencies here if needed

      - name: Run available_suttas.py script
        run: python available_suttas.py

      - name: Commit and push if changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add available_suttas.json
          git pull --rebase
          git commit -m "Update available suttas list" -a || echo "No changes to commit"
          git push
